SELECT SUBSTR(ACC.CONSTRAINT_NAME,1,15) CONSTRAINT_NAME, SUBSTR(ACC.TABLE_NAME,1,30)  TABLE_NAME, SUBSTR(ACC.COLUMN_NAME,1,15) COLUNA, ACC.POSITION
FROM ALL_CONS_COLUMNS ACC, ALL_CONSTRAINTS AC
WHERE ACC.OWNER = AC.OWNER
  AND ACC.CONSTRAINT_NAME = AC.CONSTRAINT_NAME
  AND AC.CONSTRAINT_TYPE = 'R'
  AND AC.OWNER = USER
  AND NOT EXISTS (SELECT INDEX_NAME
                  FROM ALL_IND_COLUMNS AIC
                  WHERE AIC.INDEX_OWNER = AC.OWNER
                    AND AIC.TABLE_NAME = AC.TABLE_NAME
                    --AND AIC.INDEX_NAME = AC.CONSTRAINT_NAME || '_I'
                    AND AIC.COLUMN_NAME = ACC.COLUMN_NAME)
/
