CREATE USER GONDOLA  PROFILE DEFAULT 
    IDENTIFIED BY am11go6002 DEFAULT TABLESPACE GONDOLA_PD 
    TEMPORARY TABLESPACE TEMP 
    ACCOUNT UNLOCK;
GRANT ALTER ANY PROCEDURE TO GONDOLA;
GRANT ALTER ANY SNAPSHOT TO GONDOLA;
GRANT ALTER USER TO GONDOLA;
GRANT CREATE ANY DIRECTORY TO GONDOLA;
GRANT CREATE ANY PROCEDURE TO GONDOLA WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO GONDOLA;
GRANT CREATE ANY TABLE TO GONDOLA;
GRANT CREATE ANY TRIGGER TO GONDOLA;
GRANT CREATE PUBLIC SYNONYM TO GONDOLA;
GRANT CREATE SNAPSHOT TO GONDOLA;
GRANT CREATE USER TO GONDOLA;
GRANT DEBUG ANY PROCEDURE TO GONDOLA;
GRANT DELETE ANY TABLE TO GONDOLA;
GRANT DROP ANY DIRECTORY TO GONDOLA;
GRANT DROP ANY SYNONYM TO GONDOLA;
GRANT DROP PUBLIC SYNONYM TO GONDOLA;
GRANT UNLIMITED TABLESPACE TO GONDOLA WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO GONDOLA;
GRANT SELECT ON  SYS.DBA_CONSTRAINTS TO GONDOLA;
GRANT SELECT ON  SYS.DBA_CONS_COLUMNS TO GONDOLA;
GRANT SELECT ON  SYS.DBA_JOBS TO GONDOLA;
GRANT SELECT ON  SYS.DBA_JOBS_RUNNING TO GONDOLA;
GRANT SELECT ON  SYS.DBA_SYNONYMS TO GONDOLA;
GRANT SELECT ON  SYS.DBA_USERS TO GONDOLA;
GRANT UPDATE ON  SYS.JOB$ TO GONDOLA;
GRANT CONNECT TO GONDOLA WITH ADMIN OPTION;
GRANT ROLE_GONDOLA TO GONDOLA WITH ADMIN OPTION;
